const suggestSection = document.querySelector('.suggest');
const suggestInput = suggestSection?.querySelector('input');
const suggestButton = suggestSection?.querySelector('button');
const movieContainer = document.getElementById('movieContainer');

function createMovieCard(movie) {
	const yearLabel = Number.isInteger(movie.year) ? ` (${movie.year})` : '';

	return `
		<article class="movie-card">
			<h3>${movie.title}${yearLabel}</h3>
			<p><strong>Genre:</strong> ${movie.genre}</p>
			<p>${movie.reason}</p>
		</article>
	`;
}

function renderStatus(message) {
	if (!movieContainer) {
		return;
	}

	movieContainer.innerHTML = `<p>${message}</p>`;
}

function renderSuggestions(source, suggestions) {
	if (!movieContainer) {
		return;
	}

	let sourceText = 'AI';
	if (source === 'tmdb') {
		sourceText = 'TMDB API';
	}
	if (source === 'llm+tmdb') {
		sourceText = 'LLM + TMDB API';
	}
	const cards = suggestions.map(createMovieCard).join('');

	movieContainer.innerHTML = `
		<p>Recommendations generated by: <strong>${sourceText}</strong></p>
		${cards}
	`;
}

async function handleSuggestClick() {
	const prompt = suggestInput?.value?.trim();

	if (!prompt) {
		renderStatus('Please enter a movie description first.');
		return;
	}

	if (suggestButton) {
		suggestButton.disabled = true;
		suggestButton.textContent = 'Loading...';
	}

	renderStatus('Finding recommendations...');

	try {
		const response = await fetch('/api/llm/suggest', {
			method: 'POST',
			headers: {
				'Content-Type': 'application/json',
			},
			body: JSON.stringify({ prompt, limit: 5 }),
		});

		const payload = await response.json();

		if (!response.ok) {
			throw new Error(payload.error || 'Failed to get suggestions.');
		}

		if (!Array.isArray(payload.suggestions) || payload.suggestions.length === 0) {
			renderStatus('No suggestions found. Try another description.');
			return;
		}

		renderSuggestions(payload.source, payload.suggestions);
	} catch (error) {
		renderStatus(error.message || 'Something went wrong while requesting suggestions.');
	} finally {
		if (suggestButton) {
			suggestButton.disabled = false;
			suggestButton.textContent = 'Suggest AI';
		}
	}
}

suggestButton?.addEventListener('click', handleSuggestClick);
