// Logic for handling the suggest AI feature
const suggestSection = document.querySelector('.suggest');
const suggestInput = suggestSection?.querySelector('input');
const suggestButton = suggestSection?.querySelector('button');
const movieContainer = document.getElementById('movieContainer');

function createMovieCard(movie) {
  const yearLabel = Number.isInteger(movie.year) ? ` (${movie.year})` : '';

  return `
		<article class="movie-card">
			<h3>${movie.title}${yearLabel}</h3>
			<p><strong>Genre:</strong> ${movie.genre}</p>
			<p>${movie.reason}</p>
		</article>
	`;
}

function renderStatus(message) {
  if (!movieContainer) {
    return;
  }

  movieContainer.innerHTML = `<p>${message}</p>`;
}

function renderSuggestions(source, suggestions) {
  if (!movieContainer) {
    return;
  }

  let sourceText = 'AI';
  if (source === 'tmdb') {
    sourceText = 'TMDB API';
  }
  if (source === 'llm+tmdb') {
    sourceText = 'LLM + TMDB API';
  }
  const cards = suggestions.map(createMovieCard).join('');

  movieContainer.innerHTML = `
		<p>Recommendations generated by: <strong>${sourceText}</strong></p>
		${cards}
	`;
}

async function handleSuggestClick() {
  const prompt = suggestInput?.value?.trim();

  if (!prompt) {
    renderStatus('Please enter a movie description first.');
    return;
  }

  if (suggestButton) {
    suggestButton.disabled = true;
    suggestButton.textContent = 'Loading...';
  }

  renderStatus('Finding recommendations...');

  try {
    const response = await fetch('/api/llm/suggest', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ prompt, limit: 5 }),
    });

    const payload = await response.json();

    if (!response.ok) {
      throw new Error(payload.error || 'Failed to get suggestions.');
    }

    if (
      !Array.isArray(payload.suggestions) ||
      payload.suggestions.length === 0
    ) {
      renderStatus('No suggestions found. Try another description.');
      return;
    }

    renderSuggestions(payload.source, payload.suggestions);
  } catch (error) {
    renderStatus(
      error.message || 'Something went wrong while requesting suggestions.'
    );
  } finally {
    if (suggestButton) {
      suggestButton.disabled = false;
      suggestButton.textContent = 'Suggest AI';
    }
  }
}

suggestButton?.addEventListener('click', handleSuggestClick);

// end logic for handling the suggest AI feature

//  Define UI elements
// const movieContainer = document.getElementById('movieContainer'); // Already defined above for suggest feature
const searchTypeSelect = document.querySelector('.search-type');
const searchInput = document.querySelector('.search-control input');
const searchButton = document.querySelector('.search-control button');

//  Show movies in the UI
function displayMovies(movies) {
  if (!movieContainer) return;

  if (!movies || movies.length === 0) {
    movieContainer.innerHTML =
      '<p>No movies found. Try a different search!</p>';
    return;
  }

  const cards = movies
    .map((movie) => {
      const posterUrl = movie.poster_path
        ? `https://image.tmdb.org/t/p/w300${movie.poster_path}`
        : 'https://via.placeholder.com/300x450?text=No+Poster';

      const rating = movie.vote_average ? movie.vote_average.toFixed(1) : 'N/A';

      const year = movie.release_date
        ? movie.release_date.split('-')[0]
        : 'Unknown';

      return `
      <article class="movie-card">
        <img src="${posterUrl}" alt="${movie.title}" loading="lazy" />
        <h3>${movie.title} (${year})</h3>
        <p><strong>Rating:</strong> ⭐ ${rating}</p>
        <p>${movie.overview?.slice(0, 120) || 'No description available'}...</p>
        <button class="watchlist-btn" data-id="${movie.id}">+ Add to Watchlist</button>
      </article>
    `;
    })
    .join('');

  movieContainer.innerHTML = cards;
}

//  Bring movies from the backend
async function loadMovies(type, query) {
  movieContainer.innerHTML = '<p>Fetching movies...</p>';
  try {
    const params = new URLSearchParams({ type, q: query });
    const res = await fetch(`/api/movies/search?${params}`);

    if (!res.ok) throw new Error(`Server error: ${res.status}`);

    const data = await res.json();
    displayMovies(data);
  } catch (err) {
    movieContainer.innerHTML = '<p>Something went wrong. Please try again.</p>';
    console.error('Fetch error:', err.message);
  }
}

//  Event listeners for search
searchButton?.addEventListener('click', () => {
  const type = searchTypeSelect?.value?.toLowerCase() || 'title';
  const query = searchInput?.value?.trim();

  if (!query) {
    searchInput?.focus();
    return;
  }

  loadMovies(type, query);
});

searchInput?.addEventListener('keydown', (e) => {
  if (e.key === 'Enter') searchButton?.click();
});



