// Logic for handling the suggest AI feature
const suggestSection = document.querySelector('.suggest');
const suggestInput = suggestSection?.querySelector('input');
const suggestButton = suggestSection?.querySelector('button');
const movieContainer = document.getElementById('movieContainer');

function renderStatus(message) {
  if (!movieContainer) {
    return;
  }

  movieContainer.innerHTML = `<p>${message}</p>`;
}

async function enrichAiSuggestion(movie, index) {
  const fallbackMovie = {
    id: `ai-${index}`,
    title: movie.title || 'Untitled',
    release_date: Number.isInteger(movie.year) ? `${movie.year}-01-01` : '',
    vote_average: null,
    poster_path: movie.poster_path || null,
    overview: movie.reason || 'No description available',
  };

  if (!movie?.title) {
    return fallbackMovie;
  }

  try {
    const params = new URLSearchParams({ type: 'title', q: movie.title });
    const res = await fetch(`/api/movies/search?${params}`);
    if (!res.ok) {
      return fallbackMovie;
    }

    const results = await res.json();
    if (!Array.isArray(results) || results.length === 0) {
      return fallbackMovie;
    }

    const targetYear = Number.isInteger(movie.year) ? String(movie.year) : null;
    const exactMatch = results.find((item) => {
      const itemYear = item?.release_date?.split('-')?.[0] || null;
      if (targetYear && itemYear && itemYear === targetYear) {
        return true;
      }

      return (item?.title || '').toLowerCase() === movie.title.toLowerCase();
    });

    const bestMatch = exactMatch || results[0];

    return {
      ...fallbackMovie,
      id: bestMatch?.id ?? fallbackMovie.id,
      title: bestMatch?.title || fallbackMovie.title,
      release_date: bestMatch?.release_date || fallbackMovie.release_date,
      vote_average:
        typeof bestMatch?.vote_average === 'number'
          ? bestMatch.vote_average
          : fallbackMovie.vote_average,
      poster_path: bestMatch?.poster_path || fallbackMovie.poster_path,
      overview: movie.reason || bestMatch?.overview || fallbackMovie.overview,
    };
  } catch {
    return fallbackMovie;
  }
}

async function renderSuggestions(source, suggestions) {
  if (!movieContainer) {
    return;
  }

  const normalizedSuggestions = await Promise.all(
    suggestions.map((movie, index) => enrichAiSuggestion(movie, index))
  );

  displayMovies(normalizedSuggestions);

  let sourceText = 'AI';
  if (source === 'tmdb') {
    sourceText = 'TMDB API';
  }
  if (source === 'llm+tmdb') {
    sourceText = 'LLM + TMDB API';
  }

  movieContainer.insertAdjacentHTML(
    'afterbegin',
    `<p class="recommendation-source">Recommendations generated by: <strong>${sourceText}</strong></p>`
  );
}

async function handleSuggestClick() {
  const prompt = suggestInput?.value?.trim();

  if (!prompt) {
    renderStatus('Please enter a movie description first.');
    return;
  }

  if (suggestButton) {
    suggestButton.disabled = true;
    suggestButton.textContent = 'Loading...';
  }

  renderStatus('Finding recommendations...');

  try {
    const response = await fetch('/api/llm/suggest', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ prompt, limit: 5 }),
    });

    const payload = await response.json();

    if (!response.ok) {
      throw new Error(payload.error || 'Failed to get suggestions.');
    }

    if (
      !Array.isArray(payload.suggestions) ||
      payload.suggestions.length === 0
    ) {
      renderStatus('No suggestions found. Try another description.');
      return;
    }

    await renderSuggestions(payload.source, payload.suggestions);
  } catch (error) {
    renderStatus(
      error.message || 'Something went wrong while requesting suggestions.'
    );
  } finally {
    if (suggestButton) {
      suggestButton.disabled = false;
      suggestButton.textContent = 'Suggest AI';
    }
  }
}

suggestButton?.addEventListener('click', handleSuggestClick);

// end logic for handling the suggest AI feature

//  Define UI elements
// const movieContainer = document.getElementById('movieContainer'); // Already defined above for suggest feature
const searchTypeSelect = document.querySelector('.search-type');
const searchInput = document.querySelector('.search-control input');
const searchButton = document.querySelector('.search-control button');

//  Show movies in the UI
function displayMovies(movies) {
  if (!movieContainer) return;

  if (!movies || movies.length === 0) {
    movieContainer.innerHTML =
      '<p>No movies found. Try a different search!</p>';
    return;
  }

  const cards = movies
    .map((movie) => {
      const posterUrl = movie.poster_path
        ? `https://image.tmdb.org/t/p/w300${movie.poster_path}`
        : 'https://via.placeholder.com/300x450?text=No+Poster';

      const rating = movie.vote_average ? movie.vote_average.toFixed(1) : 'N/A';

      const year = movie.release_date
        ? movie.release_date.split('-')[0]
        : 'Unknown';

      return `
      <article class="movie-card">
        <img src="${posterUrl}" alt="${movie.title}" loading="lazy" />
        <h3>${movie.title} (${year})</h3>
        <p><strong>Rating:</strong> ⭐ ${rating}</p>
        <p>${movie.overview?.slice(0, 120) || 'No description available'}...</p>
        <button class="watchlist-btn" data-id="${movie.id}">+ Add to Watchlist</button>
      </article>
    `;
    })
    .join('');

  movieContainer.innerHTML = cards;
}

//  Bring movies from the backend
async function loadMovies(type, query) {
  movieContainer.innerHTML = '<p>Fetching movies...</p>';
  try {
    const params = new URLSearchParams({ type, q: query });
    const res = await fetch(`/api/movies/search?${params}`);

    if (!res.ok) throw new Error(`Server error: ${res.status}`);

    const data = await res.json();
    displayMovies(data);
  } catch (err) {
    movieContainer.innerHTML = '<p>Something went wrong. Please try again.</p>';
    console.error('Fetch error:', err.message);
  }
}

//  Event listeners for search
searchButton?.addEventListener('click', () => {
  const type = searchTypeSelect?.value?.toLowerCase() || 'title';
  const query = searchInput?.value?.trim();

  if (!query) {
    searchInput?.focus();
    return;
  }

  loadMovies(type, query);
});

searchInput?.addEventListener('keydown', (e) => {
  if (e.key === 'Enter') searchButton?.click();
});



////// AI Recommendations Logic
document.getElementById('ai-btn')?.addEventListener('click', async () => {
  const res = await fetch('/api/movies/recommendations');
  const movies = await res.json();

  console.log(movies);
  displayMovies(movies);
});